DROP DATABASE IF EXISTS inventory_db;

CREATE DATABASE inventory_db;

USE inventory_db;

CREATE TABLE platforms (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30) NOT NULL
);

CREATE TABLE models (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  screen_size DECIMAL(3,1) NOT NULL,
  platform_id INTEGER NOT NULL REFERENCES platforms(id) ON DELETE CASCADE
);

CREATE TABLE devices (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  cond INTEGER NOT NULL CHECK (cond BETWEEN 1 AND 10),
  notes TEXT,
  date_received TIMESTAMP NOT NULL DEFAULT NOW(),
  model_id INTEGER NOT NULL REFERENCES models(id) ON DELETE CASCADE
);
